global_config:
  seed: 5959
  device: "cuda"
  is_mp: True
---
data_config:
  data_path: "/data0/xfzhang/data/NTU_RGBD_60/" # root_dir
  dataset_name: "NTU_RGBD"
  modals: ["RGB", "D"]
  num_shards: 200
  iid: True
---
server_config:
  modals: ["RGB", "D"]
  learn_strategy: "X" # X - supervised, U -unsupervised
---
clients_config:
  modals: ["RGB", "D"]
  clients_modals: # list of list, check length of clients_modals == clients_learn_strategy == clients_node
    - ["RGB", "D"]
    - ["RGB"]
    - ["D"]
  clients_learn_strategy: ["X", "X", "X"] 
  clients_nodes: [6, 6, 6] # number of nodes for each combination, [A, B], [A], [B]
---
fed_config:
  C: 0.1
  K: 20 # numbers of clients
  R: 500
  E: 10
  B: 10 # batchsize
  criterion: utils.singlem_fixmatch_loss
  optimizer: torch.optim.SGD
---
optim_config:
  lr: 0.01
  momentum: 0.9
---
init_config:
  init_type: "xavier"
  init_gain: 1.0
  gpu_ids: [0, 1, 2]
---
model_config: 
  num_modals: 2
  modals: ["RGB", "D"]
  backbone_config: # list of dictionary
    -
        modal: "RGB"
        name: TSN
        num_class: 60
        img_feature_dim: 256
    -   
        modal: "D"
        name: TSN
        num_class: 120
        img_feature_dim: 256
---
log_config:
  log_path: "./log/"
  log_name:  "baseline.log"
  tb_port: 5252
  tb_host: "0.0.0.0"
