global_config:
  seed: 5959
  device: "cuda"
  is_mp: False 
  num_workers: 4
  # is_para 
  # use_ema: False # use exponential moving average
  use_ema: True # use exponential moving average
  ema_decay: 0.9
---
data_config:
  # data_path: "/data/zhangxifan/NTU_RGBD_60/" # root_dir
  data_path: "/mnt/ssd/zhangxifan/data/NTU_RGBD_60/" # root_dir
  dataset_name: "NTU_RGBD"
  modals: ["RGB", "Depth"]
  num_shards: 200
  iid: True
---
server_config:
  modals: ["RGB", "Depth"]
  # learn_strategy: "N" # X - supervised, U - unsupervised, N - None
  learn_strategy: "X" # X - supervised, U - unsupervised, N - None
---
clients_config:
  modals: ["RGB", "Depth"]
  clients_modals: # list of list, check length of clients_modals == clients_learn_strategy == clients_node
    - ["RGB", "Depth"]
    # - ["RGB", "Depth"]
    # - ["RGB", "Depth"]
    - ["RGB"]
    - ["Depth"]
  clients_learn_strategy: ["M", "F", "F"] 
  # clients_learn_strategy: ["M", "M", "M"] 
  # clients_nodes: [6, 6, 6] # number of nodes for each combination, [A, B], [A], [B]
---
fed_config:
  C: 1.0 # fraction
  SS: 5 # server subjects
  K: 15 # numbers of clients, total 36 subjects (clients + server)
  R: 1000 # rounds
  E: 1 # local epochs
  SE: 4 # global epochs
  B: 4 # batchsize , total (mu+1)*B
  mu: 5
  criterion: torch.nn.CrossEntropyLoss
  optimizer: torch.optim.SGD
---
optim_config:
  lr: 0.001
  momentum: 0.9
---
ssl_config:
  WE: 10
  threshold: 0.9
---
init_config:
  init_type: "xavier"
  init_gain: 1.0
  gpu_ids: [0, 1]
---
model_config: 
  num_modals: 2
  modals: ["RGB", "Depth"]
  backbone_config: # list of dictionary
    -
        modal: "RGB"
        name: TSN
        base_model: "resnet18" # bs: 4~8 per gpu
        num_class: 60
    -   
        modal: "Depth"
        name: TSN
        base_model: "resnet18"
        num_class: 60
---
log_config:
  log_path: "./log/"
  log_name:  "semi-multimatch-resnet18.log"
  tb_port: 5252
  tb_host: None
